### ISSUE TITLE
Pre-index JDK's or other libraries

### ISSUE THREAD

**Issue by matozoid** [javaparser/javasymbolsolver#184]
To prevent requiring our users to add a system library to the classpath, we might want to pre-scan various JDK's and store the results in a big index file that we include with JPP, which can then be used for symbol resolution.

Giving this tool to users may speed up their symbol solving.

Good or bad idea, @ftomassetti ?

**Comment by ftomassetti** [comment]
We could do that, and that would make unnecessary to use the reflection typesolver.
I am not sure if there are minor differences between different JDKs, like the Oracle one could contain some _sun_ classes that others do not. Or it could be slightly different on different OSes (like some Look and Feel classes are different on Linux and Mac).
But maybe this is even a better reason to have those files.

The problem is: how do you list those classes? Classloaders cannot list classes, you can ask them classes by name and they give you something back (or not)

**Comment by ftomassetti** [comment]
I would say: good idea, something we should consider

**Comment by matozoid** [comment]
Idea completely stolen from Intellij, by the way, which indexes everything it can get its hands on.

**Comment by FRuffy** [comment]
I am primarily using the JavaParserTypeSolver  to parse the entire JDK because it can provide me with the full body of the declaration. Would this be possible with this approach or would the behaviour be the same as the ReflectionTypeSolver?
I know that the Oracle JDK is missing some core files of the full OpenJDK. For example sun.misc.unsafe is not available in the Oracle version. These are edge cases though, I am not sure how deep the scope is here.
Would the parser need to be aware of the OS it is running?

**Comment by matozoid** [comment]
I would say this is only for resolving, not for accessing the actual code. Maybe when this gets implemented the developer will add that feature though :)
