### ISSUE TITLE
parsing classes in the same directory / package

### ISSUE THREAD

**Issue by 4ndygu** [javaparser/javasymbolsolver#249]
Say that I'm running javaparser over some class A, but class A is using some object instance of class B in the same directory and package, so it doesn't really need an import statement. If, say, I'm looking for all Assignment Expressions and their types, how would I be able to take this into account with JavaParserTypeSolver?

pointing a JavaParserTypeSolver to the root directory works for imported resources, but not for this specific case. Maybe im missing something?

**Comment by ftomassetti** [comment]
It should work out of the box if the JavaParserTypeSolver points to the root directory, so that if you specify directory foo, and your class is in package a.b the Java file will be in directory foo/a/b. If it does not work is a bug and it should be corrected.

Could you share more details with us about this?

**Comment by 4ndygu** [comment]
Ah, really sorry - I never got to this. It seems that this was an error on my end, and not Javaparser. Thanks!
