### ISSUE TITLE
[Question] Parsing incomplete source code

### ISSUE THREAD

**Issue by ikozma** [javaparser/javasymbolsolver#284]
Hi guys!

In our project we have a very simple editor where we write Java code. Currently we are using Eclipse JDT for code completion but we want to replace it. 
Is it possible with JSS to achieve this feature? We don't want anything complex, basically when the user presses CTRL+SPACE after a "." to display the possible methods based on the type of the variable (or what is before the ".").

I started to play with JSS but for now I am facing issues because basically we have an incomplete Java source which cannot be parsed.

Thanks in advance

**Comment by matozoid** [comment]
I can answer the incomplete code part: we recently made the parser a little less hard on parse errors. You can find an article here: https://matozoid.github.io/2017/06/11/parse-error-recovery.html .

I'm actually curious how Eclipse JDT tells you that there is a place where you can complete a method like that?

For now I think your best friend would be the token list, which is reachable with `getTokenRange()` on every node. It would tell you what tokens make up that node and where they are located in the file.

I'm not sure how well JSS deals with JP's error recovery feature. @ftomassetti ?

**Comment by ftomassetti** [comment]
You could write an algorithm for autocompletion that works with incomplete code but expects the code before the caret to be correct. To support errors before the caret requires custom logic. You basically run the parser, stop when you see the caret and look at the internal state of the parser. You look at the transition exiting from that parser state and check which tokens they expect. This is basically what is done for ANTLR here: [antlr4-c3-kotlin](https://github.com/ftomassetti/antlr4-c3-kotlin).

I would not know how to do that for JavaParser, which is based on JavaCC, because I do not know well the JavaCC internals. In the case of ANTLR there is a structure named ATN that defines parser states and transitions and I used that to calculate autocompletion. Basically you take the list of tokens from the start of the document to the caret and traverse the ATN consuming the list of tokens, then you stop as you finish the tokens and at the point you look at the exit transitions from the current state. If JavaCC has something similar to the ATN we can do that, otherwise we could maybe add some hook into the parser.

**Comment by ftomassetti** [comment]
Note that this covers _structural_ autocompletion, i.e., understanding what kind of tokens can follow the caret. However you want something more complex because this algorithm would tell you that an _ID_ can follow the caret but nowhere in the grammar there is the logic to tell you that in that case the allowed IDs are the names of the methods of the right class.

**Comment by ftomassetti** [comment]
Also, in addition to specify these rules you should still build the incomplete AST for the incomplete source code and JSS would probably be not happy about the incomplete AST as it supports only well formed ASTs.

**Comment by matozoid** [comment]
@ftomassetti I think you would get quite far when JSS simply ignores nodes that are flagged unparseable.

**Comment by ikozma** [comment]
Thank you very much for the responses. I will try the first approach (handling the parse error at statement level), and I will see what will I do with the incomplete statement, anyway having a partial AST is very helpful I guess. 
I have one more small question: I was looking at the ParseErrorRecoveryTest.bodyStatementSemicolonRecovery() and noticed that if the semicolon is missing from the end of the testing statement (_int x(){X X X}_) no tree will be generated. Is this the desired behavior  or it is just a bug? I am asking this because usually when we do code completion we do not have yet the semicolon, and if it is required I will have to append it.

**Comment by matozoid** [comment]
@ikozma the only recovery currently done is "if we can't parse a statement, move forward to the next ';'" - you can check https://github.com/javaparser/javaparser/issues/582 where we have "if we can't parse some kind of body, move forward to the next '}'" which would give you an unparseable `BlockStatement` containing the tokens for `X X X`. Just open issues on that issue tracker for new recovery situations until you're happy, or convinced it will never work ;-)

**Comment by matozoid** [comment]
No answer, closing.
