### ISSUE TITLE
[Question] Getting usages of a variable.

### ISSUE THREAD

**Issue by lodart** [javaparser/javasymbolsolver#285]
Hi guys ! This is more a question than an issue : 
Is there an optimized way to find variables usages with JSS ? 
For example, if I find a `NameExpr` with JP, I can easily find the corresponding declaration with JSS. But can I do the other way ? From a Declaration (Field or Symbol) finding all NameExpr that refer to it ?

So basically, I want something like "Search Accessors" in IntelliJ. 

I could do it easily for local variables, as the search space is limited, but for Fields, it seems much more complicated.

Thank you :)

**Comment by ftomassetti** [comment]
No, there is not such thing but it could be built using JSS

**Comment by lodart** [comment]
Okay thanks :) !

**Comment by ftomassetti** [comment]
If you implement it yourself and you want help feel free to ask!

**Comment by daanschipper** [comment]
Has this feature by any chance been implemented by now? Or do you have pointers as how one could start implementing this?

**Comment by ftomassetti** [comment]
The way I would implement is by navigating the relevant ASTs, look for NameExpr, resolve them and see if they point to the variable of interest.

The problem is to figure out which code to consider. If it is a simple local variable or a parameter that is simple: only the method (or the scope where it is declared) can see it. However for fields it gets way more tricky.
