### ISSUE TITLE
Add Maven build support

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javasymbolsolver#288]

**Comment by ftomassetti** [comment]
Could you help me understanding the reasons for that?

From my point of view:

* if you are using the library maven or gradle at the same: you can use Maven in your project and add JSS as a dependency
* if you are a JSS contributor you have just to run `./gradlew assemble` to build the project and `./gradlew check` to run the test
* if for some reason you need  a pom file you can generate it by running `./gradlew generatePom`

I can see that consistency with JavaParser would be nice. I can also see that contributors that want to change the build configuration would need to know Gradle, but this is very rare. Most contributors need just to build locally the project and run tests, which can be done by typing a slightly different single command.

Aside personal preferences, why should we support Maven instead of Gradle?

We supported both of them for a while but it was just twice the effort and you can get a pom generated from gradle if you really want it.

**Comment by jimshowalter** [comment]
Most open-source Java projects support Maven. All of Apache does, I think. Making yours idiosyncratic just makes it seem kind of odd. But it's your project.

**Comment by ftomassetti** [comment]
From my understanding that are a significant portion of open-source projects that are using Gradle, therefore I do not think this looks particularly odd or exotic. Given also the implications are practically non-existent for all users and most contributors I would close this issue for the moment.
