### ISSUE TITLE
Deprecated solveType methods

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#292]
I see that the solveType methods of the JavaParserClass/Interface/EnumDeclaration have been marked Deprecated some time ago, What is the greater plan here?

I'm asking because I was trying to move some common code (e.g. getAncestors) to the JavaParserTypeAdapter and also create some new methods there (e.g. getImplementedTypes, getExtendedTypes) but quickly ran into the need for calling the solveType method.

**Comment by ftomassetti** [comment]
Good question, I should add comments for these cases. I think the idea was to remove the usage of TypeSolver from the interfaces in the model module. Also, resolution could move out of declarations, so that they are pure declarations and the resolution should work for JavaParser, Reflection and Javassist classes in the same way and not be specific to the three implementations

**Comment by sfPlayer1** [comment]
I think I'm currently running across some fallout of this while trying to implement my own TypeSolver. My application already has its own class path model that works similar to the Javassist backend in JSS, thus lending itself to be a direct data source. The deprecated methods aren't (all?) part of the interfaces, but accessed through the concrete implementation classes like in MethodResolutionLogic.solveMethodInType. This obviously breaks with any outside TypeSolver implementation.

Decoupling the declarations seems tricky... As far as I understand it, the declaration models could always yield other declarations that aren't available without further context like the (root) type solver.

For example a ReferenceTypeDeclaration backed by Javassist representing a class that implements java.util.List has to yield the j.u.List ReferenceTypeDeclaration in getInterfaces(). If List is unavailable to the Javassist backend, but behind another type solver like reflection, that other type solver is required to fill in the List ReferenceTypeDeclaration.

I don't see any other solutions besides keeping the context in the declaration field and acknowledging that declarations resolve, passing the context as a parameter to methods like getInterface() or making all declaration method output opaque. Opaque output is e.g. a List<String> of class names for getInterfaces() - needing external resolving for more insight into the classes. Passing the type solver as an argument doesn't decouple much.

(Disclaimer: I've been only looking at JSS briefly, so it's not unlikely that I'm missing something important. I however wanted to mention this quickly since this may be worth considering before merging the Java Parser PR with the existing API.)

**Comment by matozoid** [comment]
See https://github.com/javaparser/javaparser/issues/1395
