### ISSUE TITLE
Symbol Solver without files

### ISSUE THREAD

**Issue by LeanderK** [javaparser/javasymbolsolver#31]
I want to create statistics about Java Source Files. I get them over network, so in the end i have an Inputstream containing valid Java (hopefully ;) ). I thought about first running JavaParser and then the symbol-solver to get the types of the variables and the methods being called. I know i don't get 100% accuracy, but i am not aiming for this. Speed is more important. Is this possible using this project? JavaParserTypeSolver only takes the file as an argument.
Thank you

**Comment by ftomassetti** [comment]
It would require some adaptations. The problem is that to resolve types it needs to have some sort of classpath. Typically you want to specify jars files and directories for source files. Suppose you get the source code of class a.b.C which is referring class a.b.D. To solve it properly it would need a way to check if D is present among the source files and then get the corresponding model.

This is definitely doable and not particularly difficult but it would require some work.

**Comment by LeanderK** [comment]
hmm..this is more than i would need. I just need:
`List<String> x = new ArrayList();
x.add(y)`
when i have the node for x.add present i want to get the declaration `List<String> x`. I can the use the imports to figure out what the package is to get java.util.List.add() to the statistics

**Comment by ftomassetti** [comment]
sure but what if your class extends another class of which you have the source code? If you cannot find it the solver would not able to find it. Yes, you could resolve the references to the classes from the JDK but that would be it.

**Comment by LeanderK** [comment]
I am fine with that, i have to gather statistics about usages and they don't have to be accurate

**Comment by ftomassetti** [comment]
This is not something we have bandwith to work on for now
